apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-app-service
  labels:
    app: kubernetes-demo-app
spec:
  selector:
    app: kubernetes-demo-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
